default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: bloobloom_development

test:
  <<: *default
  database: bloobloom_test

production:
  <<: *default
  database: bloobloom_production
